### ISSUE TITLE
Demo seems to be broken

### ISSUE THREAD

**Issue by xori** [zrrrzzt/gun-restrict-examples#81]
* Authenticated site just spits out "Wrong user or password." in the console every time I try to login. 
  * Nothing visually happens when clicking "login" with user/pass set.
* Unauthenticated site does nothing when sending messages. (maybe intended?)
* Nothing logged in server console.

Chrome 77

Edit: I also updated the gun dependency to `0.2019.915` but that didn't seem to fix it.

**Comment by zrrrzzt** [comment]
Hi

Sorry for the inconvenience. I've kind of dropped out of the gun ecosystem and I know there's been some breaking changes regarding SEA.

If you want to try an old version this one worked https://github.com/zrrrzzt/gun-restrict-examples/releases/tag/1.2.4

I'm not sure I will update this to be a functional demo again. I will however try to remember and update the README... again: sorry :-)

**Comment by xori** [comment]
No problem, just curious if you knew or if I was doing it wrong.

Cheers
